name: Playwright Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  build:
    name: 'Firefox'
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libgbm1 libgbm-dev libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libxslt1.1
    - name: npm install
      run: |
        npm install
    - name: run firefox tests
      run: "BROWSER=firefox ./node_modules/.bin/codeceptjs run --steps"